export type { NestedKeyOf, SelectiveKeyOf, SelectiveNestedKeyOf, PartialRecord, RecursivePartial, SelectivePartial, ErrorModel, Optional, DependencyListTyped, ExtractHead, ExtractMiddle, ExtractTail, CompareFn, ArrayMinLength1, LanguageBCP47Tags, TypedArray, HTMLMediaControls, HTMLMediaState } from "./common.model";
export type { UseScriptProps, UseScript, UseScriptStatus } from './useScript.model';
export type { TextSelection } from './useTextSelection.model';
export type { UseResponsiveKeys, UseResponsiveBreakpoints } from './useResponsive.model';
export type { ConnectionState } from './useNetwork.model';
export type { BatteryStatus } from './useBattery.model';
export type { GeoLocationObject } from './useGeolocation.model';
export type { OrientationLockType, ScreenDetails, ScreenDetail, ScreenDetailsEvt } from './useScreen.model';
export type { DeviceMotionProps } from './useDeviceMotion.model';
export type { DeviceOrientationProps } from './useDeviceOrientation.model';
export type { Bluetooth, BluetoothCharacteristicProperties, BluetoothCharacteristicUUID, BluetoothDescriptorUUID, BluetoothDevice, BluetoothDevicesOptions, BluetoothRemoteGATTCharacteristic, BluetoothRemoteGATTDescriptor, BluetoothRemoteGATTServer, BluetoothRemoteGATTService, BluetoothScanFilters, BluetoothServiceUUID } from './useBluetooth.model';
export type { UseSpeechRecognitionProps, SpeechRecognition, SpeechRecognitionConfig, SpeechRecognitionState, SpeechGrammar, SpeechGrammarList, SpeechRecognitionErrorCode, SpeechRecognitionErrorEvent, SpeechRecognitionEvent } from './useSpeechRecognition.model';
export type { SpeechSynthesisSpeakParam, UseSpeechSynthesis, UseSpeechSynthesisProps } from './useSpeechSynthesis.model';
export type { UseFPSProps, UseFPSResult } from './useFPS.model';
export type { UsePointerLockProps, UsePointerLockResult } from './usePointerLock.model';
export type { UsePIPProps, UsePIPResult } from './usePIP.model';
export type { DocumentPictureInPictureEvent, DocumentPIPOptions, UseDocumentPIPProps, UseDocumentPIPResult } from './useDocumentPIP.model';
export type { UsePopoverProps, UsePopoverResult } from './usePopover.model';
export type { UseRemotePlaybackProps, UseRemotePlaybackResult } from './useRemotePlayback.model';
export type { UseAnimationProps, UseAnimationResult } from './useAnimation.model';
export type { UseAudioProps, UseAudioResult } from './useAudio.model';
export type { UseVideoProps, UseVideoResult } from './useVideo.model';
export type { UseEventSourceProps, UseEventSourceResult } from './useEventSource.model';
export type { UseWebSocketProps, UseWebSocketResult } from './useWebSocket.model';
export type { UseMediaDevicesProps, UseMediaDevicesResult, TDisplayMediaStreamOptions, CaptureController } from './useMediaDevices.model';
export type { TPermissionName, UsePermissionResult, TPermissionState } from './usePermission.model';
export type { SwipeDirection, UseSwipeProps, UseSwipeResult } from './useSwipe.model';
export type { UseWebWorkerProps, UseWebWorkerResult } from './useWebWorker.model';
export type { UseWebWorkerFnProps, UseWebWorkerFnResult } from './useWebWorkerFn.model';
export type { ToDataURLOptions, UseBase64ObjectOptions } from './getBase64.model';
export type { StateValidator } from './useStateValidator.model';
