import { defineConfig } from 'vitepress'
import { fileURLToPath } from 'url'
import { resolve, dirname } from 'path'
import react from '@vitejs/plugin-react'
import { docsPlugin, buildSidebarFromDocs, ROOT } from '../../scripts/docs-plugin.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname  = dirname(__filename)

// Sidebar is built dynamically from the .md files generated by docsPlugin()
// At first run docs/ may be empty — the plugin fills it during buildStart
const sidebar = buildSidebarFromDocs()

export default defineConfig({
	title:       'React Tools',
	description: 'A collection of Hooks, Components, Utilities and Types for React',
	lang:        'en-US',

	head: [
		['link', { rel: 'icon',                href: '/react-red.webp' }],
		['meta', { name: 'theme-color',        content: '#f53340' }],
		['meta', { property: 'og:type',        content: 'website' }],
		['meta', { property: 'og:title',       content: 'React Tools' }],
		['meta', { property: 'og:description', content: 'Hooks, Components, Utilities and Types for React' }],
		['meta', { property: 'og:image',       content: '/react-red.webp' }],
		['link', { rel: 'sitemap',             type: 'application/xml', href: '/sitemap.xml' }],
	],

	base: '/',
	cleanUrls: true,

	// VitePress built-in sitemap (generates /sitemap.xml during build)
	// We also generate one manually with our plugin for full control, but
	// enabling this adds <lastmod> and <changefreq> awareness from VitePress itself.
	// Disable to avoid duplicate – our plugin handles it with richer data.
	// sitemap: { hostname: 'https://react-tools.ndria.dev' },

	themeConfig: {
		logo: '/react-red.webp',

		nav: [
			{ text: 'Home',       link: '/' },
			{ text: 'Hooks',      link: '/hooks/state/createPubSubStore' },
			{ text: 'Components', link: '/components/ErrorBoundary' },
			{ text: 'Utils',      link: '/utils/alphanumericCompare' },
			{ text: 'Types',      link: '/types/' },
			{ text: 'npm',        link: 'https://www.npmjs.com/package/@ndriadev/react-tools' },
		],

		sidebar,

		socialLinks: [
			{ icon: 'github', link: 'https://github.com/nDriaDev/react-tools' },
		],

		footer: {
			message:   'Released under the MIT License.',
			copyright: 'Copyright © 2024-present nDriaDev',
		},

		search: { provider: 'local' }
	},

	vite: {
		plugins: [
			react(),
			docsPlugin() as any,
		],
		resolve: {
			alias: [
				// Library root alias (demo files import from '../../...' which resolves to src/)
				{
					find: '@ndriadev/react-tools',
					replacement: resolve(ROOT, 'src/index.ts'),
				},
				// assets/ is now inside src/assets – relative '../../../../assets/...' from
				// src/demo/hooks/category/tool/ resolves correctly to src/assets/
				// No alias needed; the path arithmetic already points to src/assets/
			],
		},
		optimizeDeps: {
			include: ['react', 'react-dom', 'react-dom/client'],
		},
		assetsInclude: ['**/*.mp3', '**/*.mp4'],
		build: {
			minify: true
		}
	},

	markdown: {
		lineNumbers: true,
		theme: { light: 'github-light', dark: 'github-dark' },
	}
})
